// <auto-generated />
using System;
using ArkAscendedServerAdmin.Infrastructure.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace ArkAscendedServerAdmin.Infrastructure.Data.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20261001210309_ModWebsiteUrl")]
    partial class ModWebsiteUrl
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.11");

            modelBuilder.Entity("ArkAscendedServerAdmin.Domain.BackupRecord", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("FileName")
                        .HasMaxLength(260)
                        .HasColumnType("TEXT");

                    b.Property<int>("InstanceId")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsManual")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Outcome")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("TEXT");

                    b.Property<string>("Reason")
                        .HasMaxLength(1000)
                        .HasColumnType("TEXT");

                    b.Property<long?>("SizeBytes")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("InstanceId", "CreatedAt");

                    b.ToTable("BackupRecords");
                });

            modelBuilder.Entity("ArkAscendedServerAdmin.Domain.Cluster", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("AdminWhitelist")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("ClusterKey")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("Slug")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.HasIndex("Slug")
                        .IsUnique();

                    b.ToTable("Clusters");
                });

            modelBuilder.Entity("ArkAscendedServerAdmin.Domain.ClusterMod", b =>
                {
                    b.Property<int>("ClusterId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("ModId")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("Enabled")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasDefaultValue(true);

                    b.Property<int>("Order")
                        .HasColumnType("INTEGER");

                    b.HasKey("ClusterId", "ModId");

                    b.HasIndex("ModId");

                    b.ToTable("ClusterMods");
                });

            modelBuilder.Entity("ArkAscendedServerAdmin.Domain.ExtraOverride", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("File")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("TEXT");

                    b.Property<int>("InstanceId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Key")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<string>("Section")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<string>("Value")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("InstanceId");

                    b.ToTable("ExtraOverrides");
                });

            modelBuilder.Entity("ArkAscendedServerAdmin.Domain.IniDocument", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int?>("ClusterId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("File")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("TEXT");

                    b.Property<int?>("InstanceId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Sha256")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.Property<string>("Text")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("ClusterId", "File")
                        .IsUnique();

                    b.HasIndex("InstanceId", "File")
                        .IsUnique();

                    b.ToTable("IniDocuments", t =>
                        {
                            t.HasCheckConstraint("CK_IniDocuments_SingleOwner", "(ClusterId IS NULL) <> (InstanceId IS NULL)");
                        });
                });

            modelBuilder.Entity("ArkAscendedServerAdmin.Domain.Instance", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("AdminWhitelist")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int?>("BackupIntervalMinutes")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("BackupRetention")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("ClusterId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<int>("GamePort")
                        .HasColumnType("INTEGER");

                    b.Property<DateTimeOffset?>("LastLaunchedAt")
                        .HasColumnType("TEXT");

                    b.Property<int?>("LastPid")
                        .HasColumnType("INTEGER");

                    b.Property<DateTimeOffset?>("LastProcessStartTime")
                        .HasColumnType("TEXT");

                    b.Property<int>("MapId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("MaxPlayers")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<bool>("OverridesClusterSchedule")
                        .HasColumnType("INTEGER");

                    b.Property<int>("RconPort")
                        .HasColumnType("INTEGER");

                    b.Property<string>("SessionName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<string>("Slug")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.Property<string>("State")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("ClusterId");

                    b.HasIndex("MapId");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.HasIndex("Slug")
                        .IsUnique();

                    b.ToTable("Instances");
                });

            modelBuilder.Entity("ArkAscendedServerAdmin.Domain.InstanceMod", b =>
                {
                    b.Property<int>("InstanceId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("ModId")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("Enabled")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasDefaultValue(true);

                    b.Property<int>("Order")
                        .HasColumnType("INTEGER");

                    b.HasKey("InstanceId", "ModId");

                    b.HasIndex("ModId");

                    b.ToTable("InstanceMods");
                });

            modelBuilder.Entity("ArkAscendedServerAdmin.Domain.KnownPlayer", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("EosId")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("FirstSeenAt")
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsOnline")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("LastInstanceId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTimeOffset?>("LastJoinedAt")
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset?>("LastLeftAt")
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("LastSeenAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<string>("Platform")
                        .HasMaxLength(32)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("EosId")
                        .IsUnique();

                    b.HasIndex("LastInstanceId");

                    b.ToTable("KnownPlayers");
                });

            modelBuilder.Entity("ArkAscendedServerAdmin.Domain.MaintenanceState", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Entries")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Phase")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset?>("StartedAt")
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("MaintenanceState", (string)null);
                });

            modelBuilder.Entity("ArkAscendedServerAdmin.Domain.Map", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsOfficial")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsStory")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Key")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<int?>("ModId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<DateOnly?>("ReleaseDate")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("Key")
                        .IsUnique();

                    b.ToTable("Maps");
                });

            modelBuilder.Entity("ArkAscendedServerAdmin.Domain.ModLibraryEntry", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("INTEGER");

                    b.Property<DateTimeOffset>("AddedAt")
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset?>("DateModified")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<string>("Summary")
                        .HasMaxLength(2000)
                        .HasColumnType("TEXT");

                    b.Property<string>("ThumbnailUrl")
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<string>("WebsiteUrl")
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("ModLibrary", (string)null);
                });

            modelBuilder.Entity("ArkAscendedServerAdmin.Domain.RestoreRecord", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<bool>("IncludedCluster")
                        .HasColumnType("INTEGER");

                    b.Property<int>("InstanceId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Outcome")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("TEXT");

                    b.Property<string>("Reason")
                        .HasMaxLength(1000)
                        .HasColumnType("TEXT");

                    b.Property<string>("SourceFileName")
                        .IsRequired()
                        .HasMaxLength(260)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("InstanceId", "CreatedAt");

                    b.ToTable("RestoreRecords");
                });

            modelBuilder.Entity("ArkAscendedServerAdmin.Domain.ScheduledAction", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int?>("ClusterId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Command")
                        .IsRequired()
                        .HasMaxLength(512)
                        .HasColumnType("TEXT");

                    b.Property<string>("Cron")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("TEXT");

                    b.Property<bool>("Enabled")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("InstanceId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Kind")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("TEXT");

                    b.Property<int>("WarningMinutes")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("ClusterId");

                    b.HasIndex("InstanceId");

                    b.ToTable("ScheduledActions", t =>
                        {
                            t.HasCheckConstraint("CK_ScheduledActions_SingleOwner", "(ClusterId IS NULL) <> (InstanceId IS NULL)");
                        });
                });

            modelBuilder.Entity("ArkAscendedServerAdmin.Domain.ScheduledActionRun", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTimeOffset?>("CompletedAt")
                        .HasColumnType("TEXT");

                    b.Property<int>("InstanceId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Outcome")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("TEXT");

                    b.Property<string>("Reason")
                        .IsRequired()
                        .HasMaxLength(512)
                        .HasColumnType("TEXT");

                    b.Property<int>("ScheduledActionId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTimeOffset>("ScheduledFor")
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("StartedAt")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("InstanceId", "StartedAt");

                    b.HasIndex("ScheduledActionId", "InstanceId", "ScheduledFor")
                        .IsUnique();

                    b.ToTable("ScheduledActionRuns");
                });

            modelBuilder.Entity("ArkAscendedServerAdmin.Infrastructure.Data.AppSettingRow", b =>
                {
                    b.Property<string>("Key")
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.Property<string>("Value")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Key");

                    b.ToTable("AppSettings", (string)null);
                });

            modelBuilder.Entity("ArkAscendedServerAdmin.Domain.BackupRecord", b =>
                {
                    b.HasOne("ArkAscendedServerAdmin.Domain.Instance", "Instance")
                        .WithMany("Backups")
                        .HasForeignKey("InstanceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Instance");
                });

            modelBuilder.Entity("ArkAscendedServerAdmin.Domain.Cluster", b =>
                {
                    b.OwnsOne("ArkAscendedServerAdmin.Domain.LaunchFlags", "LaunchFlags", b1 =>
                        {
                            b1.Property<int>("ClusterId")
                                .HasColumnType("INTEGER");

                            b1.Property<string>("ActiveEvent")
                                .HasMaxLength(64)
                                .HasColumnType("TEXT");

                            b1.Property<string>("AdditionalArgs")
                                .HasMaxLength(4000)
                                .HasColumnType("TEXT");

                            b1.Property<bool?>("ConvertToStore")
                                .HasColumnType("INTEGER");

                            b1.Property<bool?>("ExclusiveJoin")
                                .HasColumnType("INTEGER");

                            b1.Property<bool?>("NoBattlEye")
                                .HasColumnType("INTEGER");

                            b1.Property<bool?>("NoWildBabies")
                                .HasColumnType("INTEGER");

                            b1.Property<bool?>("ServerGameLogIncludeTribeLogs")
                                .HasColumnType("INTEGER");

                            b1.Property<string>("ServerPlatform")
                                .HasMaxLength(64)
                                .HasColumnType("TEXT");

                            b1.Property<bool?>("ServerRconOutputTribeLogs")
                                .HasColumnType("INTEGER");

                            b1.Property<bool?>("UseStore")
                                .HasColumnType("INTEGER");

                            b1.HasKey("ClusterId");

                            b1.ToTable("Clusters");

                            b1.WithOwner()
                                .HasForeignKey("ClusterId");
                        });

                    b.Navigation("LaunchFlags")
                        .IsRequired();
                });

            modelBuilder.Entity("ArkAscendedServerAdmin.Domain.ClusterMod", b =>
                {
                    b.HasOne("ArkAscendedServerAdmin.Domain.Cluster", "Cluster")
                        .WithMany("Mods")
                        .HasForeignKey("ClusterId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ArkAscendedServerAdmin.Domain.ModLibraryEntry", "Mod")
                        .WithMany()
                        .HasForeignKey("ModId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Cluster");

                    b.Navigation("Mod");
                });

            modelBuilder.Entity("ArkAscendedServerAdmin.Domain.ExtraOverride", b =>
                {
                    b.HasOne("ArkAscendedServerAdmin.Domain.Instance", "Instance")
                        .WithMany("ExtraOverrides")
                        .HasForeignKey("InstanceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Instance");
                });

            modelBuilder.Entity("ArkAscendedServerAdmin.Domain.IniDocument", b =>
                {
                    b.HasOne("ArkAscendedServerAdmin.Domain.Cluster", "Cluster")
                        .WithMany("IniDocuments")
                        .HasForeignKey("ClusterId");

                    b.HasOne("ArkAscendedServerAdmin.Domain.Instance", "Instance")
                        .WithMany("IniDocuments")
                        .HasForeignKey("InstanceId");

                    b.Navigation("Cluster");

                    b.Navigation("Instance");
                });

            modelBuilder.Entity("ArkAscendedServerAdmin.Domain.Instance", b =>
                {
                    b.HasOne("ArkAscendedServerAdmin.Domain.Cluster", "Cluster")
                        .WithMany("Instances")
                        .HasForeignKey("ClusterId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("ArkAscendedServerAdmin.Domain.Map", "Map")
                        .WithMany()
                        .HasForeignKey("MapId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.OwnsOne("ArkAscendedServerAdmin.Domain.LaunchFlags", "LaunchFlags", b1 =>
                        {
                            b1.Property<int>("InstanceId")
                                .HasColumnType("INTEGER");

                            b1.Property<string>("ActiveEvent")
                                .HasMaxLength(64)
                                .HasColumnType("TEXT");

                            b1.Property<string>("AdditionalArgs")
                                .HasMaxLength(4000)
                                .HasColumnType("TEXT");

                            b1.Property<bool?>("ConvertToStore")
                                .HasColumnType("INTEGER");

                            b1.Property<bool?>("ExclusiveJoin")
                                .HasColumnType("INTEGER");

                            b1.Property<bool?>("NoBattlEye")
                                .HasColumnType("INTEGER");

                            b1.Property<bool?>("NoWildBabies")
                                .HasColumnType("INTEGER");

                            b1.Property<bool?>("ServerGameLogIncludeTribeLogs")
                                .HasColumnType("INTEGER");

                            b1.Property<string>("ServerPlatform")
                                .HasMaxLength(64)
                                .HasColumnType("TEXT");

                            b1.Property<bool?>("ServerRconOutputTribeLogs")
                                .HasColumnType("INTEGER");

                            b1.Property<bool?>("UseStore")
                                .HasColumnType("INTEGER");

                            b1.HasKey("InstanceId");

                            b1.ToTable("Instances");

                            b1.WithOwner()
                                .HasForeignKey("InstanceId");
                        });

                    b.Navigation("Cluster");

                    b.Navigation("LaunchFlags")
                        .IsRequired();

                    b.Navigation("Map");
                });

            modelBuilder.Entity("ArkAscendedServerAdmin.Domain.InstanceMod", b =>
                {
                    b.HasOne("ArkAscendedServerAdmin.Domain.Instance", "Instance")
                        .WithMany("Mods")
                        .HasForeignKey("InstanceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ArkAscendedServerAdmin.Domain.ModLibraryEntry", "Mod")
                        .WithMany()
                        .HasForeignKey("ModId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Instance");

                    b.Navigation("Mod");
                });

            modelBuilder.Entity("ArkAscendedServerAdmin.Domain.KnownPlayer", b =>
                {
                    b.HasOne("ArkAscendedServerAdmin.Domain.Instance", "LastInstance")
                        .WithMany()
                        .HasForeignKey("LastInstanceId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("LastInstance");
                });

            modelBuilder.Entity("ArkAscendedServerAdmin.Domain.RestoreRecord", b =>
                {
                    b.HasOne("ArkAscendedServerAdmin.Domain.Instance", "Instance")
                        .WithMany("Restores")
                        .HasForeignKey("InstanceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Instance");
                });

            modelBuilder.Entity("ArkAscendedServerAdmin.Domain.ScheduledAction", b =>
                {
                    b.HasOne("ArkAscendedServerAdmin.Domain.Cluster", "Cluster")
                        .WithMany("ScheduledActions")
                        .HasForeignKey("ClusterId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("ArkAscendedServerAdmin.Domain.Instance", "Instance")
                        .WithMany("ScheduledActions")
                        .HasForeignKey("InstanceId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.Navigation("Cluster");

                    b.Navigation("Instance");
                });

            modelBuilder.Entity("ArkAscendedServerAdmin.Domain.ScheduledActionRun", b =>
                {
                    b.HasOne("ArkAscendedServerAdmin.Domain.Instance", "Instance")
                        .WithMany()
                        .HasForeignKey("InstanceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ArkAscendedServerAdmin.Domain.ScheduledAction", "ScheduledAction")
                        .WithMany("Runs")
                        .HasForeignKey("ScheduledActionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Instance");

                    b.Navigation("ScheduledAction");
                });

            modelBuilder.Entity("ArkAscendedServerAdmin.Domain.Cluster", b =>
                {
                    b.Navigation("IniDocuments");

                    b.Navigation("Instances");

                    b.Navigation("Mods");

                    b.Navigation("ScheduledActions");
                });

            modelBuilder.Entity("ArkAscendedServerAdmin.Domain.Instance", b =>
                {
                    b.Navigation("Backups");

                    b.Navigation("ExtraOverrides");

                    b.Navigation("IniDocuments");

                    b.Navigation("Mods");

                    b.Navigation("Restores");

                    b.Navigation("ScheduledActions");
                });

            modelBuilder.Entity("ArkAscendedServerAdmin.Domain.ScheduledAction", b =>
                {
                    b.Navigation("Runs");
                });
#pragma warning restore 612, 618
        }
    }
}
